'use strict'

m3.config.tiles = {
  0: {
    id: 0,
    color: '#000000',
    desc: 'void',
    icon: '&nbsp;',
    picker: {},
    randomWeight: 10,
  },
  1: {
    id: 1,
    claimType: 1,
    color: '#FFFFFF',
    desc: 'house',
    icon: '👪',
    matchable: true,
    picker: {
      active: true,
      position: 0,
    },
    randomWeight: 196,
  },
  2: {
    id: 2,
    color: '#4146db',
    desc: 'water',
    icon: '🌊',
    picker: {
      active: true,
      position: 6,
    },
    randomWeight: 196,
  },
  3: {
    id: 3,
    claimType: 2,
    color: '#edde6f',
    desc: 'field',
    icon: '🌻',
    matchable: true,
    picker: {
      active: true,
      position: 1,
    },
    randomWeight: 196,
  },
  4: {
    id: 4,
    claimType: 3,
    color: '#2d873e',
    desc: 'forest',
    icon: '🌲',
    matchable: true,
    picker: {
      active: true,
      position: 2,
    },
    randomWeight: 196,
  },
  5: {
    id: 5,
    claimType: 4,
    color: '#555555',
    desc: 'stone',
    icon: '⛰️',
    matchable: true,
    picker: {
      active: true,
      position: 3,
    },
    randomWeight: 196,
  },
  6: {
    id: 6,
    claimType: 5,
    color: '#FF9900',
    desc: 'gold',
    icon: '💎',
    picker: {},
    randomWeight: 5,
  },
  7: {
    id: 7,
    color: '#FF00FF',
    desc: 'magic',
    icon: '🧙',
    picker: {},
    randomWeight: 5,
  },
}
